"""
Reddit 创业情报站 — 模拟数据生成器
基于真实搜索到的 Reddit 创业帖子数据构建模拟数据
"""
import json
import os
import sqlite3
from datetime import datetime, timezone

DATA_DIR = os.path.join(os.path.dirname(__file__), "..", "data")
os.makedirs(DATA_DIR, exist_ok=True)

# 基于真实 Reddit 创业帖子构建的模拟数据
MOCK_POSTS = [
    {
        "id": "saas_001",
        "subreddit": "SaaS",
        "title": "Our todo app hit $200K MRR after 18 months — here's what we learned about retention",
        "author": "saasfounder2024",
        "score": 847,
        "num_comments": 156,
        "upvote_ratio": 0.94,
        "url": "",
        "selftext": "We started as a simple task manager for remote teams. After pivoting to AI-powered scheduling, our MRR went from $12K to $200K in 14 months. Key learnings: 1) Focus on one integration (Slack first, then expand). 2) Freemium kills conversion — we switched to 14-day trial. 3) Churn dropped from 8% to 3% when we added team analytics. Tech stack: Next.js, PostgreSQL, Stripe, OpenAI API. Built by 3-person team. We're now at 4,200 paying customers. AMA.",
        "created_utc": 1750000000,
        "permalink": "https://www.reddit.com/r/SaaS/comments/saas_001/",
        "extracted_summary": "Our todo app hit $200K MRR after 18 months — here's what we learned about retention. We started as a simple task manager...",
        "has_revenue_info": 1,
        "revenue_pattern": "$200K MRR, $12K",
        "tech_stack": "next.js, postgres, stripe, openai",
        "target_audience": "team, remote",
        "pain_point": "retention, churn",
        "sentiment": "positive",
        "category": "revenue_share",
        "fetched_at": "2025-06-17T02:00:00+00:00",
        "extracted_at": "2025-06-17T02:00:00+00:00",
        "created_date": "2025-06-10"
    },
    {
        "id": "saas_002",
        "subreddit": "SaaS",
        "title": "How I grew MRR from $80K to $340K in 14 months — a detailed breakdown",
        "author": "growthhacker_saas",
        "score": 623,
        "num_comments": 89,
        "upvote_ratio": 0.91,
        "url": "",
        "selftext": "This is a detailed breakdown of how we 4x'd our MRR. Stage 1 ($80K-$150K): Hired 2 SDRs, focused on outbound. Stage 2 ($150K-$250K): Launched self-serve pricing, reduced sales friction. Stage 3 ($250K-$340K): Added enterprise tier at $2K/mo. Key metrics: CAC $180, LTV $4,200, NRR 118%. We used Clay for outbound, Stripe for billing, Mixpanel for analytics. Bootstrapped — no VC funding. Founders: 2 technical, 1 sales.",
        "created_utc": 1749900000,
        "permalink": "https://www.reddit.com/r/SaaS/comments/saas_002/",
        "extracted_summary": "How I grew MRR from $80K to $340K in 14 months — a detailed breakdown. This is a detailed breakdown of how we 4x'd our MRR...",
        "has_revenue_info": 1,
        "revenue_pattern": "$80K, $340K, $150K, $250K, $2K/mo",
        "tech_stack": "stripe",
        "target_audience": "enterprise",
        "pain_point": "sales friction",
        "sentiment": "positive",
        "category": "revenue_share",
        "fetched_at": "2025-06-17T02:00:00+00:00",
        "extracted_at": "2025-06-17T02:00:00+00:00",
        "created_date": "2025-06-09"
    },
    {
        "id": "ih_001",
        "subreddit": "indiehackers",
        "title": "Photo AI by Pieter Levels: $0 to $132K MRR in 18 months — complete case study",
        "author": "indie_researcher",
        "score": 1240,
        "num_comments": 312,
        "upvote_ratio": 0.97,
        "url": "https://www.indiehackers.com/post/photo-ai-by-pieter-levels",
        "selftext": "Complete deep dive into Photo AI. Revenue milestones: Week 1: $5.4K MRR. Month 2: $28.7K. Month 5: $61.8K (1,872 customers). Month 14: $64-77K. Month 19: $100K. Month 33: $132-138K. Annual run rate: $1.58M-$1.65M. Costs: ~$13K/mo (Replicate API GPU $12K, DigitalOcean VPS $40, domain/misc $1K). Profit margin: 87%+. Tech: PHP, jQuery, Bootstrap, SQLite (single file). No framework, no React. Hosted on a single VPS. Solo founder. No employees. Built and shipped in 2 weeks.",
        "created_utc": 1749700000,
        "permalink": "https://www.reddit.com/r/indiehackers/comments/ih_001/",
        "extracted_summary": "Photo AI by Pieter Levels: $0 to $132K MRR in 18 months — complete case study. Complete deep dive into Photo AI. Revenue milestones...",
        "has_revenue_info": 1,
        "revenue_pattern": "$132K MRR, $5.4K, $28.7K, $61.8K, $100K, $1.58M",
        "tech_stack": "php, sqlite, bootstrap, digitalocean",
        "target_audience": "developer, creator",
        "pain_point": "",
        "sentiment": "positive",
        "category": "revenue_share",
        "fetched_at": "2025-06-17T02:00:00+00:00",
        "extracted_at": "2025-06-17T02:00:00+00:00",
        "created_date": "2025-06-07"
    },
    {
        "id": "ih_002",
        "subreddit": "indiehackers",
        "title": "From failed SaaS to $14K MRR software-enabled service — here's the pivot story",
        "author": "tyler_scionti",
        "score": 892,
        "num_comments": 178,
        "upvote_ratio": 0.95,
        "url": "",
        "selftext": "I built a SaaS product. It wasn't a success. So I pivoted to a software-enabled service — using the tool internally to deliver services. Now at $14K MRR. The lesson: sometimes the product isn't the business, the service is. We do social media management for B2B brands, powered by our internal tool. 12 customers at $1,200-$2,500/mo. Tech: Python/Django, Postgres, Tailwind, AWS. Built solo, now have 1 contractor. Self-funded, profitable from month 3.",
        "created_utc": 1749600000,
        "permalink": "https://www.reddit.com/r/indiehackers/comments/ih_002/",
        "extracted_summary": "From failed SaaS to $14K MRR software-enabled service — here's the pivot story. I built a SaaS product. It wasn't a success...",
        "has_revenue_info": 1,
        "revenue_pattern": "$14K MRR, $1,200-$2,500/mo",
        "tech_stack": "python, django, postgres, tailwind, aws",
        "target_audience": "b2b, brand",
        "pain_point": "failed SaaS",
        "sentiment": "positive",
        "category": "lessons_learned",
        "fetched_at": "2025-06-17T02:00:00+00:00",
        "extracted_at": "2025-06-17T02:00:00+00:00",
        "created_date": "2025-06-06"
    },
    {
        "id": "ih_003",
        "subreddit": "indiehackers",
        "title": "Indie hacker making $40K MRR with an AI wrapper — no code, no team",
        "author": "ai_wrapper_guy",
        "score": 756,
        "num_comments": 245,
        "upvote_ratio": 0.89,
        "url": "",
        "selftext": "I built an AI wrapper SaaS using no-code tools. It takes PDFs and extracts structured data using GPT-4. $40K MRR, 2,800 customers. Built with Bubble, Make, Airtable, and OpenAI API. No coding knowledge. Started as a side project while working full-time. Quit my job at $8K MRR. Now fully focused. Marketing: Reddit, Twitter, and one Product Hunt launch. Most customers come from organic search. Charging $29-$99/mo. No VC, no employees, no office. Just me and a laptop.",
        "created_utc": 1749500000,
        "permalink": "https://www.reddit.com/r/indiehackers/comments/ih_003/",
        "extracted_summary": "Indie hacker making $40K MRR with an AI wrapper — no code, no team. I built an AI wrapper SaaS using no-code tools...",
        "has_revenue_info": 1,
        "revenue_pattern": "$40K MRR, $8K MRR, $29-$99/mo",
        "tech_stack": "openai, bubble, airtable",
        "target_audience": "developer, freelancer",
        "pain_point": "extract structured data",
        "sentiment": "positive",
        "category": "revenue_share",
        "fetched_at": "2025-06-17T02:00:00+00:00",
        "extracted_at": "2025-06-17T02:00:00+00:00",
        "created_date": "2025-06-05"
    },
    {
        "id": "startup_001",
        "subreddit": "startups",
        "title": "KeepTheScore — solo dev, $9,580 MRR, $22,555 total revenue in January 2025",
        "author": "caspar_vw",
        "score": 534,
        "num_comments": 67,
        "upvote_ratio": 0.92,
        "url": "https://www.keepthescore.co",
        "selftext": "I'm Caspar, solo developer of KeepTheScore (scoreboard tool for events and games). Revenue journey: $26K in 2022 -> $140,100 in 2024. Currently at $9,580 MRR. January 2025: $22,555 total revenue. Bootstrapped, no funding, no employees. Marketing: SEO + word of mouth. Tech stack: Ruby on Rails, PostgreSQL, Heroku. I built this as a side project while working at a startup. Went full-time at $4K MRR. Lessons: 1) Niche tools can be surprisingly big. 2) SEO is everything for B2C tools. 3) Don't over-engineer — I still use Bootstrap 4.",
        "created_utc": 1749400000,
        "permalink": "https://www.reddit.com/r/startups/comments/startup_001/",
        "extracted_summary": "KeepTheScore — solo dev, $9,580 MRR, $22,555 total revenue in January 2025. I'm Caspar, solo developer of KeepTheScore...",
        "has_revenue_info": 1,
        "revenue_pattern": "$9,580 MRR, $22,555, $26K, $140,100, $4K MRR",
        "tech_stack": "ruby, rails, postgres, heroku, bootstrap",
        "target_audience": "developer, event organizer",
        "pain_point": "over-engineer",
        "sentiment": "positive",
        "category": "revenue_share",
        "fetched_at": "2025-06-17T02:00:00+00:00",
        "extracted_at": "2025-06-17T02:00:00+00:00",
        "created_date": "2025-06-04"
    },
    {
        "id": "startup_002",
        "subreddit": "startups",
        "title": "I made $65K from my MVP development service — $10K MRR, $160K total revenue as of April 2025",
        "author": "mvp_dev_guy",
        "score": 445,
        "num_comments": 98,
        "upvote_ratio": 0.90,
        "url": "",
        "selftext": "I offer MVP development for non-technical founders. $5K-$15K per project. Currently at $10K MRR with 3 active clients. $160K total revenue since starting in 2023. I use a fixed template: React + Next.js + Supabase + Stripe + Vercel. Can ship most MVPs in 2-4 weeks. Target audience: founders who want to validate an idea before hiring. Marketing: Twitter (build in public), Indie Hackers, and referrals from past clients. No cold outreach. Just shipped my 24th MVP. 18 of them are still active (founders kept building).",
        "created_utc": 1749300000,
        "permalink": "https://www.reddit.com/r/startups/comments/startup_002/",
        "extracted_summary": "I made $65K from my MVP development service — $10K MRR, $160K total revenue as of April 2025. I offer MVP development for non-technical founders...",
        "has_revenue_info": 1,
        "revenue_pattern": "$65K, $10K MRR, $160K, $5K-$15K",
        "tech_stack": "react, next.js, supabase, stripe, vercel",
        "target_audience": "founder, non-technical",
        "pain_point": "validate an idea",
        "sentiment": "positive",
        "category": "revenue_share",
        "fetched_at": "2025-06-17T02:00:00+00:00",
        "extracted_at": "2025-06-17T02:00:00+00:00",
        "created_date": "2025-06-03"
    },
    {
        "id": "entrepreneur_001",
        "subreddit": "Entrepreneur",
        "title": "My solopreneur story: $0 to $65,000/month in 2 years",
        "author": "solopreneur_journey",
        "score": 1203,
        "num_comments": 203,
        "upvote_ratio": 0.96,
        "url": "",
        "selftext": "Year 1: $0. Quit my job as a marketing manager. Started a content agency. Fired my first client (toxic). Lost $15K on a failed e-commerce experiment. Year 2: $15K/mo. Narrowed to SEO + content for SaaS. Hired 2 contractors. $35K/mo. Added link building. $65K/mo. Now at $65K/mo with 8 team members (all contractors). Profit margin: 45%. I work 35 hours/week. Key: niche down early. I was a generalist for 8 months and made nothing. The moment I said 'I only do SEO for SaaS' everything changed. No office. No VC. No debt.",
        "created_utc": 1749200000,
        "permalink": "https://www.reddit.com/r/Entrepreneur/comments/entrepreneur_001/",
        "extracted_summary": "My solopreneur story: $0 to $65,000/month in 2 years. Year 1: $0. Quit my job as a marketing manager. Started a content agency...",
        "has_revenue_info": 1,
        "revenue_pattern": "$65,000/month, $15K/mo, $35K/mo, $0",
        "tech_stack": "",
        "target_audience": "saas",
        "pain_point": "niche down",
        "sentiment": "positive",
        "category": "lessons_learned",
        "fetched_at": "2025-06-17T02:00:00+00:00",
        "extracted_at": "2025-06-17T02:00:00+00:00",
        "created_date": "2025-06-02"
    },
    {
        "id": "sideproject_001",
        "subreddit": "SideProject",
        "title": "Launched a directory submission tool, hit $500 MRR in 45 days with zero budget",
        "author": "sideproject_launcher",
        "score": 378,
        "num_comments": 54,
        "upvote_ratio": 0.88,
        "url": "",
        "selftext": "Built a directory submission tool that auto-submits startups to 100+ directories. $500 MRR in 45 days. Solo founder, bootstrapped. Tools used: Fathom Analytics (analytics), Tally (forms), Frill (feedback/roadmap), Supabase (backend), Next.js (frontend). Spent $0 on ads. All traffic from Reddit, Indie Hackers, and Product Hunt. 87 paid users at $5.99/mo. Churn: 12% (high but improving). Next: add AI-generated descriptions for each directory. Currently working on it part-time while employed. Plan to go full-time at $2K MRR.",
        "created_utc": 1749100000,
        "permalink": "https://www.reddit.com/r/SideProject/comments/sideproject_001/",
        "extracted_summary": "Launched a directory submission tool, hit $500 MRR in 45 days with zero budget. Built a directory submission tool that auto-submits startups to 100+ directories...",
        "has_revenue_info": 1,
        "revenue_pattern": "$500 MRR, $5.99/mo, $2K MRR",
        "tech_stack": "next.js, supabase, fathom analytics",
        "target_audience": "startup, founder",
        "pain_point": "zero budget",
        "sentiment": "positive",
        "category": "launch",
        "fetched_at": "2025-06-17T02:00:00+00:00",
        "extracted_at": "2025-06-17T02:00:00+00:00",
        "created_date": "2025-06-01"
    },
    {
        "id": "sideproject_002",
        "subreddit": "SideProject",
        "title": "18 days after launch, almost at $100 MRR — build in public works",
        "author": "bip_newbie",
        "score": 256,
        "num_comments": 43,
        "upvote_ratio": 0.91,
        "url": "",
        "selftext": "I built a tool for developers to quickly generate API documentation from code comments. Launched 18 days ago. 17 paid users, $99 MRR. Pricing: $9/mo solo, $29/mo team. Marketing: built in public on Twitter and Reddit. Posted daily updates. Tech: React, Node.js, MongoDB, hosted on Railway. The key was solving a real problem I had — I was tired of writing docs manually. Next steps: add OpenAPI spec generation, integrate with GitHub Actions. Solo founder, working full-time job, coding at nights. Grateful for the community support.",
        "created_utc": 1749000000,
        "permalink": "https://www.reddit.com/r/SideProject/comments/sideproject_002/",
        "extracted_summary": "18 days after launch, almost at $100 MRR — build in public works. I built a tool for developers to quickly generate API documentation...",
        "has_revenue_info": 1,
        "revenue_pattern": "$100 MRR, $99 MRR, $9/mo, $29/mo",
        "tech_stack": "react, node.js, mongodb",
        "target_audience": "developer",
        "pain_point": "tired of writing docs manually",
        "sentiment": "positive",
        "category": "launch",
        "fetched_at": "2025-06-17T02:00:00+00:00",
        "extracted_at": "2025-06-17T02:00:00+00:00",
        "created_date": "2025-05-31"
    },
    {
        "id": "bootstrapped_001",
        "subreddit": "bootstrapped",
        "title": "Broke the $1.5M ARR mark as an agency of one — here's how I structure my offers",
        "author": "agency_of_one",
        "score": 567,
        "num_comments": 112,
        "upvote_ratio": 0.93,
        "url": "",
        "selftext": "I'm a single-person agency doing SEO + content strategy for B2B SaaS. $1.5M ARR. No employees, no contractors. How: 1) Productized services — 3 fixed packages ($5K, $12K, $25K/mo). 2) Retainer-only, no project work. 3) 12 clients max, all 12+ month contracts. 4) I do the strategy, outsource execution to white-label partners. Tools: Notion, Loom, Stripe, Calendly. I work 4 hours/day on client work, 2 hours on business development. 8 years of experience before going solo. The $25K package is new — only 2 clients, but it's 33% of revenue.",
        "created_utc": 1748900000,
        "permalink": "https://www.reddit.com/r/bootstrapped/comments/bootstrapped_001/",
        "extracted_summary": "Broke the $1.5M ARR mark as an agency of one — here's how I structure my offers. I'm a single-person agency doing SEO + content strategy...",
        "has_revenue_info": 1,
        "revenue_pattern": "$1.5M ARR, $5K, $12K, $25K/mo",
        "tech_stack": "notion, stripe",
        "target_audience": "b2b, saas",
        "pain_point": "",
        "sentiment": "positive",
        "category": "revenue_share",
        "fetched_at": "2025-06-17T02:00:00+00:00",
        "extracted_at": "2025-06-17T02:00:00+00:00",
        "created_date": "2025-05-30"
    },
    {
        "id": "bootstrapped_002",
        "subreddit": "bootstrapped",
        "title": "$8K MRR within a year after pivoting from SaaS to productized services",
        "author": "moniet_sawhney",
        "score": 412,
        "num_comments": 76,
        "upvote_ratio": 0.90,
        "url": "",
        "selftext": "I spent 18 months building a SaaS for freelancers. $200 MRR, couldn't get traction. Pivoted to a productized service: done-for-you LinkedIn profiles for founders. $8K MRR within 12 months. The SaaS was solving a real problem (profile optimization), but freelancers didn't want to DIY. They wanted it done for them. Lesson: sometimes the same solution works better as a service. 23 clients at $300-$500/mo. I use a simple process: intake form, 1-week turnaround, 2 revision rounds. Tools: Airtable, Typeform, Canva, Notion. No code. Just systems.",
        "created_utc": 1748800000,
        "permalink": "https://www.reddit.com/r/bootstrapped/comments/bootstrapped_002/",
        "extracted_summary": "$8K MRR within a year after pivoting from SaaS to productized services. I spent 18 months building a SaaS for freelancers...",
        "has_revenue_info": 1,
        "revenue_pattern": "$8K MRR, $200 MRR, $300-$500/mo",
        "tech_stack": "airtable, notion",
        "target_audience": "founder, freelancer",
        "pain_point": "couldn't get traction",
        "sentiment": "positive",
        "category": "lessons_learned",
        "fetched_at": "2025-06-17T02:00:00+00:00",
        "extracted_at": "2025-06-17T02:00:00+00:00",
        "created_date": "2025-05-29"
    },
    {
        "id": "startup_ideas_001",
        "subreddit": "Startup_Ideas",
        "title": "AI-powered legal document review for rental contracts — validated with 50 beta users",
        "author": "legaltech_builder",
        "score": 189,
        "num_comments": 67,
        "upvote_ratio": 0.85,
        "url": "",
        "selftext": "I built an AI tool that reviews rental contracts and flags risky clauses (e.g., 'excessive penalty', 'unfavorable jurisdiction'). Focused on rental contracts niche. 50 beta users in 2 weeks. Tech: Llama 3 + LangChain RAG + PDF parsing + Stripe. Launch cost: $800. Pricing: $19.99/mo. Currently 400+ paying users. MRR: $8,000+. Acquired through Reddit LegalTech subreddit free trial (first 3 pages free). Then word-of-mouth through lawyer communities. Solo founder, former lawyer, self-taught programming. Key insight: narrow niche beats broad horizontal every time.",
        "created_utc": 1748700000,
        "permalink": "https://www.reddit.com/r/Startup_Ideas/comments/startup_ideas_001/",
        "extracted_summary": "AI-powered legal document review for rental contracts — validated with 50 beta users. I built an AI tool that reviews rental contracts and flags risky clauses...",
        "has_revenue_info": 1,
        "revenue_pattern": "$19.99/mo, $8,000 MRR, $800",
        "tech_stack": "llama 3, langchain, stripe, python",
        "target_audience": "lawyer, freelancer",
        "pain_point": "risky clauses",
        "sentiment": "positive",
        "category": "idea_validation",
        "fetched_at": "2025-06-17T02:00:00+00:00",
        "extracted_at": "2025-06-17T02:00:00+00:00",
        "created_date": "2025-05-28"
    },
    {
        "id": "startup_ideas_002",
        "subreddit": "Startup_Ideas",
        "title": "Should I build this? — AI tool that generates TEMU-compliant product descriptions in 8 languages",
        "author": "ecommerce_dev",
        "score": 234,
        "num_comments": 89,
        "upvote_ratio": 0.82,
        "url": "",
        "selftext": "I work with cross-border ecommerce sellers. They spend hours writing product descriptions for Amazon, TEMU, etc. I want to build an AI tool that: 1) Takes product keywords, 2) Generates descriptions matching each platform's rules (e.g., TEMU keyword density requirements), 3) Supports 8 languages (EN, CN, JP, DE, etc.). Pricing: $9.9/mo solo, $49/mo enterprise (batch). I've talked to 12 sellers, 8 said they'd pay. No competitors doing the platform-rule-aware generation. Tech stack: Qwen-Max + templates + Shopify API. Is this worth building? Any feedback on pricing or features?",
        "created_utc": 1748600000,
        "permalink": "https://www.reddit.com/r/Startup_Ideas/comments/startup_ideas_002/",
        "extracted_summary": "Should I build this? — AI tool that generates TEMU-compliant product descriptions in 8 languages. I work with cross-border ecommerce sellers...",
        "has_revenue_info": 0,
        "revenue_pattern": "",
        "tech_stack": "qwen-max, shopify api, python",
        "target_audience": "ecommerce, seller",
        "pain_point": "spend hours writing product descriptions",
        "sentiment": "neutral",
        "category": "idea_validation",
        "fetched_at": "2025-06-17T02:00:00+00:00",
        "extracted_at": "2025-06-17T02:00:00+00:00",
        "created_date": "2025-05-27"
    },
    {
        "id": "experienceddevs_001",
        "subreddit": "ExperiencedDevs",
        "title": "How we scaled our SaaS from 1K to 100K users on a single Postgres instance",
        "author": "senior_architect",
        "score": 678,
        "num_comments": 134,
        "upvote_ratio": 0.94,
        "url": "",
        "selftext": "We run a B2B SaaS with 100K users on a single PostgreSQL instance (RDS db.r6g.2xlarge). No sharding, no read replicas. Here's how: 1) Aggressive indexing — 200+ indexes, all partial. 2) Connection pooling via PgBouncer. 3) Query optimization — reduced N+1 queries by 95%. 4) Materialized views for analytics. 5) Partitioning for time-series data. 6) Async everything — webhooks, emails, exports. 7) Caching: Redis for hot data, CloudFront for static. Monthly DB cost: $800. We could scale 3x more before needing to shard. Tech: Django, Postgres, Redis, AWS. Team: 3 backend engineers. Don't over-engineer your database early.",
        "created_utc": 1748500000,
        "permalink": "https://www.reddit.com/r/ExperiencedDevs/comments/experienceddevs_001/",
        "extracted_summary": "How we scaled our SaaS from 1K to 100K users on a single Postgres instance. We run a B2B SaaS with 100K users on a single PostgreSQL instance...",
        "has_revenue_info": 0,
        "revenue_pattern": "",
        "tech_stack": "postgres, redis, django, aws, pgbouncer, cloudfront",
        "target_audience": "developer, team",
        "pain_point": "over-engineer your database",
        "sentiment": "positive",
        "category": "tech_stack",
        "fetched_at": "2025-06-17T02:00:00+00:00",
        "extracted_at": "2025-06-17T02:00:00+00:00",
        "created_date": "2025-05-26"
    },
    {
        "id": "experienceddevs_002",
        "subreddit": "ExperiencedDevs",
        "title": "I used Twitter to build my startup and made $3.5K on launch day",
        "author": "twitter_builder",
        "score": 345,
        "num_comments": 78,
        "upvote_ratio": 0.89,
        "url": "",
        "selftext": "I documented my entire journey on Twitter from 0 to 30K followers. Built a SaaS for collecting testimonials (Famewall). Launch day: $3.5K in sales. Pre-launch strategy: 1) Shared weekly builds for 3 months. 2) Created a waitlist with 800+ people. 3) Offered 50% lifetime discount for first 48 hours. 4) Posted on Product Hunt, Hacker News, Reddit. Tech: React, Firebase, Stripe. The Twitter audience was the #1 driver — 60% of sales came from followers. Lesson: building in public on Twitter is the most effective free marketing for indie hackers. No ad spend. No cold outreach. Just consistent sharing.",
        "created_utc": 1748400000,
        "permalink": "https://www.reddit.com/r/ExperiencedDevs/comments/experienceddevs_002/",
        "extracted_summary": "I used Twitter to build my startup and made $3.5K on launch day. I documented my entire journey on Twitter from 0 to 30K followers...",
        "has_revenue_info": 1,
        "revenue_pattern": "$3.5K, $3,000 MRR, $25,000 ARR",
        "tech_stack": "react, firebase, stripe",
        "target_audience": "developer, indie hacker",
        "pain_point": "",
        "sentiment": "positive",
        "category": "growth_marketing",
        "fetched_at": "2025-06-17T02:00:00+00:00",
        "extracted_at": "2025-06-17T02:00:00+00:00",
        "created_date": "2025-05-25"
    },
    {
        "id": "saas_003",
        "subreddit": "SaaS",
        "title": "Why our $2M ARR SaaS is still running on a single $80/month VPS",
        "author": "frugal_cto",
        "score": 912,
        "num_comments": 201,
        "upvote_ratio": 0.95,
        "url": "",
        "selftext": "We're a $2M ARR SaaS with 15K customers. Our entire infrastructure runs on a single Hetzner VPS (€80/mo). No Kubernetes, no microservices, no serverless. Just a monolithic app (Ruby on Rails) + Postgres + Redis + Nginx. Why: 1) Simplicity = reliability. 2. We handle 2M requests/day with 99.97% uptime. 3. One box is easier to debug than 50. We have a backup server for failover. Costs: Server €80, Backup €20, Monitoring €15, CDN €30. Total: ~€145/mo. Compare to AWS: we'd pay $3K+/mo for the same. We have 2 engineers. They understand the entire stack. No DevOps team. No cloud complexity. Just boring technology that works.",
        "created_utc": 1748300000,
        "permalink": "https://www.reddit.com/r/SaaS/comments/saas_003/",
        "extracted_summary": "Why our $2M ARR SaaS is still running on a single $80/month VPS. We're a $2M ARR SaaS with 15K customers. Our entire infrastructure runs on a single Hetzner VPS...",
        "has_revenue_info": 1,
        "revenue_pattern": "$2M ARR, $80/month, €80, $3K+/mo",
        "tech_stack": "ruby, rails, postgres, redis, nginx",
        "target_audience": "developer, team",
        "pain_point": "cloud complexity",
        "sentiment": "positive",
        "category": "tech_stack",
        "fetched_at": "2025-06-17T02:00:00+00:00",
        "extracted_at": "2025-06-17T02:00:00+00:00",
        "created_date": "2025-05-24"
    },
    {
        "id": "saas_004",
        "subreddit": "SaaS",
        "title": "Churn is killing us — dropped from 5% to 2% after implementing these 3 changes",
        "author": "churn_fighter",
        "score": 534,
        "num_comments": 123,
        "upvote_ratio": 0.88,
        "url": "",
        "selftext": "We were losing customers at 5% monthly churn. At that rate, you're effectively replacing your entire customer base every 20 months. Here's what we changed: 1) Added annual billing with 2 months free. 40% of new customers chose annual. 2) Built a cancellation flow that asks 'why' and offers alternatives. 30% of cancels were saved. 3) Implemented usage-based alerts — when a customer hits 80% of their plan, we email them with an upgrade offer. Churn dropped to 2%. Net revenue retention went from 95% to 108%. MRR is $45K. ARR is $540K. 12-person team. This took 6 months to implement properly. Worth every hour.",
        "created_utc": 1748200000,
        "permalink": "https://www.reddit.com/r/SaaS/comments/saas_004/",
        "extracted_summary": "Churn is killing us — dropped from 5% to 2% after implementing these 3 changes. We were losing customers at 5% monthly churn...",
        "has_revenue_info": 1,
        "revenue_pattern": "$45K MRR, $540K ARR, 5%, 2%",
        "tech_stack": "",
        "target_audience": "saas",
        "pain_point": "churn is killing us",
        "sentiment": "positive",
        "category": "growth_marketing",
        "fetched_at": "2025-06-17T02:00:00+00:00",
        "extracted_at": "2025-06-17T02:00:00+00:00",
        "created_date": "2025-05-23"
    },
    {
        "id": "indiehackers_004",
        "subreddit": "indiehackers",
        "title": "$250K in 1 year as a solo founder — the full playbook",
        "author": "solo_250k",
        "score": 1567,
        "num_comments": 298,
        "upvote_ratio": 0.97,
        "url": "",
        "selftext": "I made $250K in my first year as a solo founder. Here's the playbook: Month 1-2: Built a simple SaaS for dentists (appointment reminders). Charged $49/mo. 5 customers. Month 3-6: Added SMS, reviews, payments. $200/mo tier. 20 customers. Month 7-9: Added AI chatbot. $500/mo tier. 35 customers. Month 10-12: White-label option. $1,000/mo. 50 customers total. $250K revenue. Tech: Next.js, Supabase, Twilio, Stripe, OpenAI. Marketing: cold email to dental offices. No ads. 1,200 emails sent, 50 replies, 25 demos, 15 conversions. 50% close rate. Then referrals took over. Now at 80 customers. $350K projected this year. Solo. No employees. Work 40 hours/week. Profit margin: 70%.",
        "created_utc": 1748100000,
        "permalink": "https://www.reddit.com/r/indiehackers/comments/indiehackers_004/",
        "extracted_summary": "$250K in 1 year as a solo founder — the full playbook. I made $250K in my first year as a solo founder. Here's the playbook...",
        "has_revenue_info": 1,
        "revenue_pattern": "$250K, $49/mo, $200/mo, $500/mo, $1,000/mo, $350K, $350K",
        "tech_stack": "next.js, supabase, twilio, stripe, openai",
        "target_audience": "dentist, small business",
        "pain_point": "",
        "sentiment": "positive",
        "category": "revenue_share",
        "fetched_at": "2025-06-17T02:00:00+00:00",
        "extracted_at": "2025-06-17T02:00:00+00:00",
        "created_date": "2025-05-22"
    },
    {
        "id": "entrepreneur_002",
        "subreddit": "Entrepreneur",
        "title": "I Used Twitter To Build My Startup And Made $3.5K On Launch Day — step by step",
        "author": "gouthamjay8",
        "score": 445,
        "num_comments": 91,
        "upvote_ratio": 0.87,
        "url": "",
        "selftext": "I built Famewall, a SaaS for collecting testimonials to boost revenue. Here's exactly how I used Twitter to launch: Step 1: Tweeted every day for 90 days about my journey. Step 2: Built a following of 5K+ engaged followers. Step 3: Created a waitlist with a simple landing page. Step 4: Offered 50% lifetime discount for 48 hours. Step 5: Announced launch on Twitter, Product Hunt, and Hacker News. Results: $3.5K on launch day. $3,000 MRR by month 3. $25,000+ ARR currently. 400+ paying customers. Key insight: building in public is the most effective free marketing. Your struggles are content. Your wins are content. Just share.",
        "created_utc": 1748000000,
        "permalink": "https://www.reddit.com/r/Entrepreneur/comments/entrepreneur_002/",
        "extracted_summary": "I Used Twitter To Build My Startup And Made $3.5K On Launch Day — step by step. I built Famewall, a SaaS for collecting testimonials...",
        "has_revenue_info": 1,
        "revenue_pattern": "$3.5K, $3,000 MRR, $25,000 ARR, $25,000+ ARR",
        "tech_stack": "",
        "target_audience": "developer, startup",
        "pain_point": "",
        "sentiment": "positive",
        "category": "growth_marketing",
        "fetched_at": "2025-06-17T02:00:00+00:00",
        "extracted_at": "2025-06-17T02:00:00+00:00",
        "created_date": "2025-05-21"
    },
    {
        "id": "sideproject_003",
        "subreddit": "SideProject",
        "title": "Launching a no-code tool for non-technical founders to build landing pages",
        "author": "nocode_builder",
        "score": 167,
        "num_comments": 45,
        "upvote_ratio": 0.83,
        "url": "https://www.mypage.app",
        "selftext": "I built a simple landing page builder for non-technical founders. Drag-and-drop, pre-built templates, Stripe integration, email capture. Built with Webflow + Airtable + Make. No coding required. Just launched today. 12 signups in 2 hours. Would love feedback from the community. Questions: 1) What features should I prioritize? 2) Is $19/mo a fair price? 3) Should I add AI copy generation? I'm a designer by trade, first time building a product. Excited but nervous. Any advice welcome.",
        "created_utc": 1747900000,
        "permalink": "https://www.reddit.com/r/SideProject/comments/sideproject_003/",
        "extracted_summary": "Launching a no-code tool for non-technical founders to build landing pages. I built a simple landing page builder for non-technical founders...",
        "has_revenue_info": 0,
        "revenue_pattern": "",
        "tech_stack": "webflow, airtable, make, stripe",
        "target_audience": "founder, non-technical, designer",
        "pain_point": "non-technical founders",
        "sentiment": "neutral",
        "category": "launch",
        "fetched_at": "2025-06-17T02:00:00+00:00",
        "extracted_at": "2025-06-17T02:00:00+00:00",
        "created_date": "2025-05-20"
    },
    {
        "id": "startup_003",
        "subreddit": "startups",
        "title": "Looking for a co-founder — technical, AI/ML background, equity split discussion",
        "author": "nontechnical_founder",
        "score": 89,
        "num_comments": 156,
        "upvote_ratio": 0.76,
        "url": "",
        "selftext": "I'm a non-technical founder with 8 years of experience in B2B sales. I have a validated idea for an AI sales assistant (10 paying pilot customers, $2K MRR). I need a technical co-founder with AI/ML experience. The product is technically complex — LLM fine-tuning, RAG pipeline, real-time integrations. I'm offering 40% equity. Is this fair? I'm bringing: validated idea, 10 pilot customers, $2K MRR, industry expertise, sales network. Seeking: full-time technical lead, AI/ML expertise, full-stack dev skills. Based in SF but remote OK. DM me if interested.",
        "created_utc": 1747800000,
        "permalink": "https://www.reddit.com/r/startups/comments/startup_003/",
        "extracted_summary": "Looking for a co-founder — technical, AI/ML background, equity split discussion. I'm a non-technical founder with 8 years of experience in B2B sales...",
        "has_revenue_info": 1,
        "revenue_pattern": "$2K MRR, 40% equity",
        "tech_stack": "llm, rag",
        "target_audience": "b2b, sales",
        "pain_point": "non-technical founder",
        "sentiment": "neutral",
        "category": "hiring_team",
        "fetched_at": "2025-06-17T02:00:00+00:00",
        "extracted_at": "2025-06-17T02:00:00+00:00",
        "created_date": "2025-05-19"
    },
    {
        "id": "saas_005",
        "subreddit": "SaaS",
        "title": "Lessons from my first failed SaaS — $30K spent, 0 customers, 1 year of my life",
        "author": "failed_but_wiser",
        "score": 723,
        "num_comments": 187,
        "upvote_ratio": 0.93,
        "url": "",
        "selftext": "I spent $30K and a year building a project management tool for construction companies. Zero customers. Here's what I did wrong: 1) Didn't talk to a single construction manager before building. Assumed I knew the problem. 2) Over-engineered — built a mobile app, web app, API, integrations. Should have been a simple web form. 3) No distribution plan. Built it, tweeted about it once, expected users to come. 4) Pricing was random — $99/mo with no basis. 5) Didn't have a niche — tried to serve all construction, from residential to commercial to industrial. Lesson: validate before you build. The problem is never the technology. It's always the market. Now working on a micro-SaaS for a niche I actually understand. 12 beta users already.",
        "created_utc": 1747700000,
        "permalink": "https://www.reddit.com/r/SaaS/comments/saas_005/",
        "extracted_summary": "Lessons from my first failed SaaS — $30K spent, 0 customers, 1 year of my life. I spent $30K and a year building a project management tool...",
        "has_revenue_info": 1,
        "revenue_pattern": "$30K, $99/mo, 0 customers",
        "tech_stack": "",
        "target_audience": "construction",
        "pain_point": "didn't talk to a single construction manager",
        "sentiment": "negative",
        "category": "lessons_learned",
        "fetched_at": "2025-06-17T02:00:00+00:00",
        "extracted_at": "2025-06-17T02:00:00+00:00",
        "created_date": "2025-05-18"
    },
    {
        "id": "bootstrapped_003",
        "subreddit": "bootstrapped",
        "title": "Vertical AI tools for dentists, roofers, locksmiths will murder generic horizontal apps",
        "author": "vertical_ai_believer",
        "score": 567,
        "num_comments": 134,
        "upvote_ratio": 0.91,
        "url": "",
        "selftext": "I believe the next wave of AI SaaS winners will be vertical-specific, not horizontal. Here's why: 1) Horizontal AI tools (like generic AI writers) are commodities. Anyone can build them. 2) Vertical AI has domain expertise baked in. A dentist AI knows ADA codes, insurance rules, patient flow. A roofer AI knows local permits, material specs, weather data. 3) Vertical AI can charge 5-10x more because the ROI is immediate and measurable. 4) Less competition — most devs build horizontal because it's 'easier to scale'. But vertical is easier to sell. Examples: Clearwave (dental AI) — $50M ARR. Roofr (roofing AI) — $10M ARR. Jobber (trades) — $100M+ ARR. All bootstrapped or lightly funded. The playbook: pick a vertical you know, build an AI tool that does 80% of a specific job, charge $200-$1,000/mo. No VC needed.",
        "created_utc": 1747600000,
        "permalink": "https://www.reddit.com/r/bootstrapped/comments/bootstrapped_003/",
        "extracted_summary": "Vertical AI tools for dentists, roofers, locksmiths will murder generic horizontal apps. I believe the next wave of AI SaaS winners will be vertical-specific...",
        "has_revenue_info": 1,
        "revenue_pattern": "$50M ARR, $10M ARR, $100M+ ARR, $200-$1,000/mo",
        "tech_stack": "",
        "target_audience": "dentist, developer, roofer",
        "pain_point": "horizontal AI tools are commodities",
        "sentiment": "positive",
        "category": "idea_validation",
        "fetched_at": "2025-06-17T02:00:00+00:00",
        "extracted_at": "2025-06-17T02:00:00+00:00",
        "created_date": "2025-05-17"
    },
    {
        "id": "experienceddevs_003",
        "subreddit": "ExperiencedDevs",
        "title": "How to choose your tech stack for a bootstrapped SaaS in 2025 — a decision framework",
        "author": "stack_advisor",
        "score": 456,
        "num_comments": 98,
        "upvote_ratio": 0.90,
        "url": "",
        "selftext": "I see this question every day: 'What stack should I use?' Here's my framework after building 3 bootstrapped SaaS products: 1) Speed > Scale. You need to ship in 2 weeks, not 2 months. Pick what you know, not what's trendy. 2) Monolith > Microservices. One codebase, one database, one server. Scale later. 3) Boring > Bleeding edge. Postgres, Redis, React. Not the new JS framework. 4) Self-hosted > Cloud. Hetzner/Vultr $5/mo vs AWS $200/mo for the same. 5) API-first > Platform-first. Stripe for billing, Postmark for email, Twilio for SMS. Don't build what you can buy. My recommended stack: Backend: Python/Django or Node/Express. Frontend: React or Next.js. DB: PostgreSQL. Hosting: Hetzner or Railway. Auth: Supabase Auth or Auth0. Billing: Stripe. Email: Postmark. Analytics: Plausible or Fathom. Total monthly cost at launch: $50-$100. This scales to $1M ARR easily.",
        "created_utc": 1747500000,
        "permalink": "https://www.reddit.com/r/ExperiencedDevs/comments/experienceddevs_003/",
        "extracted_summary": "How to choose your tech stack for a bootstrapped SaaS in 2025 — a decision framework. I see this question every day: 'What stack should I use?'...",
        "has_revenue_info": 1,
        "revenue_pattern": "$50-$100, $1M ARR, $5/mo, $200/mo",
        "tech_stack": "python, django, node, express, react, next.js, postgres, redis, supabase, stripe, postmark, twilio, plausible, fathom",
        "target_audience": "developer, founder",
        "pain_point": "what stack should I use",
        "sentiment": "positive",
        "category": "tech_stack",
        "fetched_at": "2025-06-17T02:00:00+00:00",
        "extracted_at": "2025-06-17T02:00:00+00:00",
        "created_date": "2025-05-16"
    },
    {
        "id": "startup_ideas_003",
        "subreddit": "Startup_Ideas",
        "title": "Would you pay $29/mo for an AI tool that automates your daily standup notes?",
        "author": "standup_ai_guy",
        "score": 123,
        "num_comments": 87,
        "upvote_ratio": 0.71,
        "url": "",
        "selftext": "I hate writing standup notes. Every day, same format. I built an AI tool that connects to your GitHub, Jira, Slack, and writes your standup notes automatically. It knows what you worked on, what you're blocked on, and what you're doing next. Currently in beta with 5 friends. All 5 love it. Pricing: $9/mo for individuals, $29/mo for teams. Questions: 1) Is this a real pain point for you? 2) Would you pay $29/mo? 3) What integrations should I add? Tech: OpenAI API + LangChain + GitHub API + Slack API. Built in 2 weeks. No customers yet. Just validating. Be honest — is this a real business or a feature?",
        "created_utc": 1747400000,
        "permalink": "https://www.reddit.com/r/Startup_Ideas/comments/startup_ideas_003/",
        "extracted_summary": "Would you pay $29/mo for an AI tool that automates your daily standup notes? I hate writing standup notes. Every day, same format...",
        "has_revenue_info": 0,
        "revenue_pattern": "$29/mo, $9/mo",
        "tech_stack": "openai, langchain, github api, slack api",
        "target_audience": "developer, team",
        "pain_point": "hate writing standup notes",
        "sentiment": "neutral",
        "category": "idea_validation",
        "fetched_at": "2025-06-17T02:00:00+00:00",
        "extracted_at": "2025-06-17T02:00:00+00:00",
        "created_date": "2025-05-15"
    },
    {
        "id": "entrepreneur_003",
        "subreddit": "Entrepreneur",
        "title": "The dark side of selling digital products — what no one tells you about burnout",
        "author": "burned_out_builder",
        "score": 892,
        "num_comments": 245,
        "upvote_ratio": 0.94,
        "url": "",
        "selftext": "I built a $15K MRR digital product business. Solo. For 3 years. It broke me. Here's what nobody talks about: 1) Isolation. Working alone for 3 years, I lost most of my friends. 2) Anxiety. Every bad review felt like a personal attack. I couldn't sleep. 3) No off switch. When you own the business, you're always on. Vacations? I checked support tickets on the beach. 4) No safety net. No salary, no benefits, no 401k. If I got sick, the business stopped. 5) Imposter syndrome. Even at $15K MRR, I felt like a fraud. I sold the business for $300K. Best decision I ever made. Now I work as a consultant, $200/hr, 20 hours/week. I have weekends. I have friends. I sleep. My advice: don't glorify the grind. Build a business that serves your life, not the other way around.",
        "created_utc": 1747300000,
        "permalink": "https://www.reddit.com/r/Entrepreneur/comments/entrepreneur_003/",
        "extracted_summary": "The dark side of selling digital products — what no one tells you about burnout. I built a $15K MRR digital product business. Solo. For 3 years...",
        "has_revenue_info": 1,
        "revenue_pattern": "$15K MRR, $300K, $200/hr, $15K MRR",
        "tech_stack": "",
        "target_audience": "developer, solopreneur",
        "pain_point": "burnout, isolation, anxiety",
        "sentiment": "negative",
        "category": "lessons_learned",
        "fetched_at": "2025-06-17T02:00:00+00:00",
        "extracted_at": "2025-06-17T02:00:00+00:00",
        "created_date": "2025-05-14"
    },
    {
        "id": "indiehackers_005",
        "subreddit": "indiehackers",
        "title": "Building a successful niche product as a wedge into a bigger market — $8K MRR story",
        "author": "neel_bhattacharya",
        "score": 678,
        "num_comments": 145,
        "upvote_ratio": 0.92,
        "url": "",
        "selftext": "I saw an opportunity before AI was ready to handle it. So I waited. When the tech caught up, I built a wedge. Now at $8K MRR. The niche: AI-powered contract review for real estate lawyers. The wedge: a simple tool that flags risky clauses. The bigger market: full legal workflow automation. Strategy: 1) Start narrow. Real estate contracts only. 2) Build trust. 50 beta users, all lawyers. 3) Expand. Now adding commercial leases, employment contracts. 4) Scale. White-label for law firms. Tech: Python, LangChain, OpenAI, Next.js, Postgres. Solo founder. 18 months to $8K MRR. Next target: $20K MRR by adding 2 more verticals. The lesson: patience is a competitive advantage. I could have built this 2 years ago with worse AI. I waited. It was worth it.",
        "created_utc": 1747200000,
        "permalink": "https://www.reddit.com/r/indiehackers/comments/indiehackers_005/",
        "extracted_summary": "Building a successful niche product as a wedge into a bigger market — $8K MRR story. I saw an opportunity before AI was ready to handle it...",
        "has_revenue_info": 1,
        "revenue_pattern": "$8K MRR, $20K MRR, $8K MRR",
        "tech_stack": "python, langchain, openai, next.js, postgres",
        "target_audience": "lawyer, real estate",
        "pain_point": "risky clauses",
        "sentiment": "positive",
        "category": "revenue_share",
        "fetched_at": "2025-06-17T02:00:00+00:00",
        "extracted_at": "2025-06-17T02:00:00+00:00",
        "created_date": "2025-05-13"
    },
    {
        "id": "saas_006",
        "subreddit": "SaaS",
        "title": "We raised prices 50% and churn actually went DOWN — here's the psychology",
        "author": "pricing_psychologist",
        "score": 445,
        "num_comments": 98,
        "upvote_ratio": 0.86,
        "url": "",
        "selftext": "We raised our prices 50% (from $49 to $79/mo). Everyone on our team thought we'd lose customers. We lost 2. Churn went from 4.5% to 3.8%. Revenue per customer went up 42%. Here's why it worked: 1) We grandfathered existing customers. No one felt forced. 2) We added 2 new features the week before the price increase. Perceived value went up. 3) We communicated it as 'we're growing with you' not 'we need more money'. 4) We added an annual plan with 3 months free. 35% of new customers chose annual. The lesson: your price is probably too low. Most founders undercharge because they're scared. Test higher prices. The market can handle it. $79 is still cheap for B2B. We might go to $129 next year. ARR is $1.2M. 1,200 customers. 8-person team.",
        "created_utc": 1747100000,
        "permalink": "https://www.reddit.com/r/SaaS/comments/saas_006/",
        "extracted_summary": "We raised prices 50% and churn actually went DOWN — here's the psychology. We raised our prices 50% (from $49 to $79/mo)...",
        "has_revenue_info": 1,
        "revenue_pattern": "$49, $79/mo, $1.2M ARR, $129, $49",
        "tech_stack": "",
        "target_audience": "b2b, saas",
        "pain_point": "undercharge",
        "sentiment": "positive",
        "category": "revenue_share",
        "fetched_at": "2025-06-17T02:00:00+00:00",
        "extracted_at": "2025-06-17T02:00:00+00:00",
        "created_date": "2025-05-12"
    },
    {
        "id": "startup_004",
        "subreddit": "startups",
        "title": "Just got rejected by YC for the 3rd time — should I keep applying or just build?",
        "author": "yc_rejected",
        "score": 567,
        "num_comments": 234,
        "upvote_ratio": 0.85,
        "url": "",
        "selftext": "Applied to YC 3 times. Rejected all 3. Different ideas each time. Current idea: AI-powered customer support for ecommerce. 15 pilot customers, $3K MRR. Bootstrapped. Team: 2 founders (both technical). We're debating: 1) Apply to YC again (W25 batch). 2) Skip YC, keep bootstrapping. 3) Apply to other accelerators (Techstars, 500). We don't need the money ($3K MRR covers rent). We want the network and credibility. But 3 rejections is a pattern. Maybe YC just isn't for us. Advice from founders who got rejected and still succeeded? Or should we just build and prove them wrong? Feeling discouraged but not defeated.",
        "created_utc": 1747000000,
        "permalink": "https://www.reddit.com/r/startups/comments/startup_004/",
        "extracted_summary": "Just got rejected by YC for the 3rd time — should I keep applying or just build? Applied to YC 3 times. Rejected all 3...",
        "has_revenue_info": 1,
        "revenue_pattern": "$3K MRR",
        "tech_stack": "",
        "target_audience": "ecommerce",
        "pain_point": "rejected by YC",
        "sentiment": "negative",
        "category": "hiring_team",
        "fetched_at": "2025-06-17T02:00:00+00:00",
        "extracted_at": "2025-06-17T02:00:00+00:00",
        "created_date": "2025-05-11"
    },
    {
        "id": "bootstrapped_004",
        "subreddit": "bootstrapped",
        "title": "Solo founder, $7K MRR in 18 months with a freelancer toolkit — here's the breakdown",
        "author": "freelancer_toolkit_guy",
        "score": 389,
        "num_comments": 67,
        "upvote_ratio": 0.88,
        "url": "",
        "selftext": "I built a toolkit for freelancers: contracts, invoicing, time tracking, proposal templates. $7K MRR in 18 months. Solo founder. 450 customers. Pricing: $15/mo solo, $39/mo pro. Breakdown: Month 1-6: $0-$500. Built MVP, posted on Reddit. Month 7-12: $500-$3K. Added invoicing feature, word of mouth. Month 13-18: $3K-$7K. Added team plan, white-label option. Marketing: 70% organic search, 20% Reddit, 10% referrals. Tech: Next.js, Supabase, Stripe, Resend. Costs: $200/mo infrastructure. Profit margin: 85%. I work 30 hours/week. The rest is automated. Key: I was a freelancer for 5 years. I knew the pain points intimately. If you're not your own customer, find one and shadow them.",
        "created_utc": 1746900000,
        "permalink": "https://www.reddit.com/r/bootstrapped/comments/bootstrapped_004/",
        "extracted_summary": "Solo founder, $7K MRR in 18 months with a freelancer toolkit — here's the breakdown. I built a toolkit for freelancers: contracts, invoicing...",
        "has_revenue_info": 1,
        "revenue_pattern": "$7K MRR, $15/mo, $39/mo, $500, $3K, $200/mo, $7K MRR",
        "tech_stack": "next.js, supabase, stripe, resend",
        "target_audience": "freelancer, solopreneur",
        "pain_point": "contracts, invoicing, time tracking",
        "sentiment": "positive",
        "category": "revenue_share",
        "fetched_at": "2025-06-17T02:00:00+00:00",
        "extracted_at": "2025-06-17T02:00:00+00:00",
        "created_date": "2025-05-10"
    },
    {
        "id": "experienceddevs_004",
        "subreddit": "ExperiencedDevs",
        "title": "Why I moved from AWS to Hetzner and saved $2,800/month on infrastructure",
        "author": "cloud_cost_cutter",
        "score": 723,
        "num_comments": 156,
        "upvote_ratio": 0.93,
        "url": "",
        "selftext": "We were paying $3,200/month on AWS for a mid-sized SaaS (EC2, RDS, S3, CloudFront, Lambda). Moved to Hetzner. Now paying $420/month. Same traffic, same performance. Here's the breakdown: AWS: EC2 ($800) + RDS ($1,200) + S3 ($200) + CloudFront ($300) + ElastiCache ($400) + misc ($300) = $3,200. Hetzner: 2x CPX51 servers ($250) + 1x dedicated DB server ($120) + Object Storage ($50) = $420. We lost managed services but gained $2,800/month. The migration took 2 weeks. We scripted the entire thing. Downtime: 0 minutes (blue-green). Lesson: cloud providers are convenient but expensive. For bootstrapped SaaS, self-hosted VPS is often better. We're at $800K ARR. That $2,800/month is 3.5% of our revenue. Significant for a bootstrapped team.",
        "created_utc": 1746800000,
        "permalink": "https://www.reddit.com/r/ExperiencedDevs/comments/experienceddevs_004/",
        "extracted_summary": "Why I moved from AWS to Hetzner and saved $2,800/month on infrastructure. We were paying $3,200/month on AWS for a mid-sized SaaS...",
        "has_revenue_info": 1,
        "revenue_pattern": "$3,200/month, $420/month, $2,800/month, $800K ARR, $2,800/month",
        "tech_stack": "aws, ec2, rds, s3, cloudfront, lambda, hetzner",
        "target_audience": "developer, team",
        "pain_point": "cloud providers are expensive",
        "sentiment": "positive",
        "category": "tech_stack",
        "fetched_at": "2025-06-17T02:00:00+00:00",
        "extracted_at": "2025-06-17T02:00:00+00:00",
        "created_date": "2025-05-09"
    },
    {
        "id": "sideproject_004",
        "subreddit": "SideProject",
        "title": "I built a Chrome extension that blocks distracting sites during focus time — 200 users in week 1",
        "author": "focus_extension_dev",
        "score": 234,
        "num_comments": 45,
        "upvote_ratio": 0.87,
        "url": "",
        "selftext": "Built a simple Chrome extension that blocks distracting sites (Reddit, Twitter, YouTube) during scheduled focus times. You set the schedule, it blocks. No willpower needed. 200 users in the first week. All organic from Reddit and Product Hunt. Free for now, planning to add premium features ($4.99/mo): custom block lists, analytics, sync across devices. Tech: vanilla JS, Chrome APIs, Firebase. Built in 3 days. Cost: $0. No backend. Just a browser extension. 200 users, 4.8 star rating. Next: add Firefox support, then Safari. Maybe add a mobile app later. This is my 5th side project. The others failed. This one stuck because I use it every day. Dogfooding matters.",
        "created_utc": 1746700000,
        "permalink": "https://www.reddit.com/r/SideProject/comments/sideproject_004/",
        "extracted_summary": "I built a Chrome extension that blocks distracting sites during focus time — 200 users in week 1. Built a simple Chrome extension...",
        "has_revenue_info": 0,
        "revenue_pattern": "$4.99/mo",
        "tech_stack": "javascript, firebase, chrome api",
        "target_audience": "developer, freelancer",
        "pain_point": "distracting sites",
        "sentiment": "positive",
        "category": "launch",
        "fetched_at": "2025-06-17T02:00:00+00:00",
        "extracted_at": "2025-06-17T02:00:00+00:00",
        "created_date": "2025-05-08"
    },
    {
        "id": "entrepreneur_004",
        "subreddit": "Entrepreneur",
        "title": "I broke $1.5M ARR as a single-person agency — here's my offer structure",
        "author": "agency_of_one_v2",
        "score": 678,
        "num_comments": 134,
        "upvote_ratio": 0.91,
        "url": "",
        "selftext": "Single-person agency doing SEO + content for B2B SaaS. $1.5M ARR. No employees. How: 1) Productized services — 3 fixed packages ($5K, $12K, $25K/mo). 2) Retainer-only, no project work. 3) 12 clients max, all 12+ month contracts. 4) I do the strategy, outsource execution to white-label partners. 5) 8 years of experience before going solo. I work 4 hours/day on client work, 2 hours on business development. Tools: Notion, Loom, Stripe, Calendly. The $25K package is 33% of revenue. I built this over 3 years. Year 1: $200K. Year 2: $600K. Year 3: $1.5M. The key was saying no to 90% of opportunities. Niche down hard. I only work with B2B SaaS companies between $1M-$10M ARR. No exceptions.",
        "created_utc": 1746600000,
        "permalink": "https://www.reddit.com/r/Entrepreneur/comments/entrepreneur_004/",
        "extracted_summary": "I broke $1.5M ARR as a single-person agency — here's my offer structure. Single-person agency doing SEO + content for B2B SaaS...",
        "has_revenue_info": 1,
        "revenue_pattern": "$1.5M ARR, $5K, $12K, $25K/mo, $200K, $600K, $1.5M ARR",
        "tech_stack": "notion, stripe, calendly",
        "target_audience": "b2b, saas",
        "pain_point": "",
        "sentiment": "positive",
        "category": "revenue_share",
        "fetched_at": "2025-06-17T02:00:00+00:00",
        "extracted_at": "2025-06-17T02:00:00+00:00",
        "created_date": "2025-05-07"
    },
    {
        "id": "startup_ideas_004",
        "subreddit": "Startup_Ideas",
        "title": "Idea: AI tool that predicts which SaaS features will increase revenue before you build them",
        "author": "data_driven_founder",
        "score": 345,
        "num_comments": 78,
        "upvote_ratio": 0.84,
        "url": "",
        "selftext": "Idea: An AI tool that analyzes your user behavior data, feature requests, and competitor landscape to predict which new features will have the highest revenue impact. Inputs: user analytics, support tickets, churn reasons, competitor features, market trends. Output: ranked feature list with predicted revenue impact and confidence score. Use case: instead of guessing what to build next, you use data. I've been doing this manually for my SaaS and it's been surprisingly accurate. Built a simple spreadsheet model. 80% of my top predictions were correct. Would this be useful? I'm a data scientist by background. Could build this as a standalone SaaS or integrate with existing analytics tools (Amplitude, Mixpanel, etc.). Pricing: $99/mo for startups, $499/mo for enterprise. Looking for beta testers. 10 slots available.",
        "created_utc": 1746500000,
        "permalink": "https://www.reddit.com/r/Startup_Ideas/comments/startup_ideas_004/",
        "extracted_summary": "Idea: AI tool that predicts which SaaS features will increase revenue before you build them. Idea: An AI tool that analyzes your user behavior data...",
        "has_revenue_info": 0,
        "revenue_pattern": "$99/mo, $499/mo",
        "tech_stack": "",
        "target_audience": "startup, data scientist",
        "pain_point": "guessing what to build next",
        "sentiment": "neutral",
        "category": "idea_validation",
        "fetched_at": "2025-06-17T02:00:00+00:00",
        "extracted_at": "2025-06-17T02:00:00+00:00",
        "created_date": "2025-05-06"
    },
    {
        "id": "saas_007",
        "subreddit": "SaaS",
        "title": "Our API-first approach: how we built a $5M ARR SaaS with 0 sales team",
        "author": "api_first_cto",
        "score": 567,
        "num_comments": 123,
        "upvote_ratio": 0.91,
        "url": "",
        "selftext": "We built a $5M ARR API-first SaaS. No sales team. No marketing team. Just product-led growth. The product: a PDF processing API. Developers integrate it. Self-serve signup. Credit card required. Pricing: $0.01/page, volume discounts at scale. 85% of revenue comes from API usage. 15% from dashboard plans. We have 2,300 paying customers. Average revenue per customer: $180/mo. Top 10 customers: $50K/mo combined. Tech: Go, Postgres, Redis, Kubernetes, AWS. 6 engineers. No sales, no marketing, no customer success. Just docs, SDKs, and a great API. The product sells itself. Word of mouth from developers. Listed on RapidAPI. We answer support tickets in <2 hours. That's it. $5M ARR. 87% gross margin.",
        "created_utc": 1746400000,
        "permalink": "https://www.reddit.com/r/SaaS/comments/saas_007/",
        "extracted_summary": "Our API-first approach: how we built a $5M ARR SaaS with 0 sales team. We built a $5M ARR API-first SaaS. No sales team...",
        "has_revenue_info": 1,
        "revenue_pattern": "$5M ARR, $0.01/page, $180/mo, $50K/mo, $5M ARR, 87%",
        "tech_stack": "go, postgres, redis, kubernetes, aws",
        "target_audience": "developer",
        "pain_point": "",
        "sentiment": "positive",
        "category": "revenue_share",
        "fetched_at": "2025-06-17T02:00:00+00:00",
        "extracted_at": "2025-06-17T02:00:00+00:00",
        "created_date": "2025-05-05"
    },
    {
        "id": "indiehackers_006",
        "subreddit": "indiehackers",
        "title": "From $0 to $3,000 MRR in 90 days — a complete launch playbook",
        "author": "launch_playbook_author",
        "score": 890,
        "num_comments": 156,
        "upvote_ratio": 0.94,
        "url": "",
        "selftext": "Complete playbook for launching a SaaS from $0 to $3K MRR in 90 days. Week 1-2: Build a simple landing page with Carrd. Add Stripe checkout. No product yet. Just validation. Week 3-4: Share on Reddit, Twitter, Indie Hackers. Collect 50+ email signups. Week 5-6: Build MVP. One core feature. Ship in 2 weeks. Week 7-8: Launch on Product Hunt. Email waitlist. Offer 50% discount for first 48 hours. Week 9-10: Collect feedback, iterate. Add 1 feature per week. Week 11-12: Content marketing. Write 3 blog posts about the problem you solve. Week 13: $3K MRR. My actual numbers: launched a tool for collecting testimonials. $0 -> $3K MRR in 87 days. 200 customers. $15/mo average. Tech: React, Firebase, Stripe. Marketing: Twitter (build in public), Product Hunt, Reddit. No ads. No cold email. No SEO. Just community.",
        "created_utc": 1746300000,
        "permalink": "https://www.reddit.com/r/indiehackers/comments/indiehackers_006/",
        "extracted_summary": "From $0 to $3,000 MRR in 90 days — a complete launch playbook. Complete playbook for launching a SaaS from $0 to $3K MRR in 90 days...",
        "has_revenue_info": 1,
        "revenue_pattern": "$3K MRR, $3,000 MRR, $15/mo, $0",
        "tech_stack": "react, firebase, stripe",
        "target_audience": "developer, founder",
        "pain_point": "",
        "sentiment": "positive",
        "category": "growth_marketing",
        "fetched_at": "2025-06-17T02:00:00+00:00",
        "extracted_at": "2025-06-17T02:00:00+00:00",
        "created_date": "2025-05-04"
    },
    {
        "id": "experienceddevs_005",
        "subreddit": "ExperiencedDevs",
        "title": "How to handle the 'build vs buy' decision for auth, billing, and email in 2025",
        "author": "build_vs_buy_expert",
        "score": 445,
        "num_comments": 89,
        "upvote_ratio": 0.89,
        "url": "",
        "selftext": "After building 5 SaaS products, here's my build vs buy framework for the most common decisions: Auth: BUY. Use Supabase Auth, Auth0, or Clerk. Building auth is a security nightmare. Billing: BUY. Use Stripe. Don't build your own billing system. It's complex and regulated. Email: BUY. Use Postmark, Resend, or Mailgun. Don't build SMTP. Analytics: BUY. Use Plausible or Fathom. Don't build GA4 alternative. Search: BUILD. Most products don't need Algolia. Postgres full-text search is enough. Notifications: BUILD. Simple webhook system. No need for Pusher. File storage: BUY. Use S3 or R2. Don't build your own CDN. The rule: if it's not core to your product, buy it. If it's core, build it. Core = what your customers pay for. Auth, billing, email are not core. They're infrastructure. Spend 90% of your time on the 10% that matters.",
        "created_utc": 1746200000,
        "permalink": "https://www.reddit.com/r/ExperiencedDevs/comments/experienceddevs_005/",
        "extracted_summary": "How to handle the 'build vs buy' decision for auth, billing, and email in 2025. After building 5 SaaS products, here's my build vs buy framework...",
        "has_revenue_info": 0,
        "revenue_pattern": "",
        "tech_stack": "supabase, auth0, stripe, postmark, resend, mailgun, plausible, fathom, postgres, s3, r2",
        "target_audience": "developer, founder",
        "pain_point": "build vs buy decision",
        "sentiment": "positive",
        "category": "tech_stack",
        "fetched_at": "2025-06-17T02:00:00+00:00",
        "extracted_at": "2025-06-17T02:00:00+00:00",
        "created_date": "2025-05-03"
    },
    {
        "id": "startup_005",
        "subreddit": "startups",
        "title": "Should I raise a seed round or keep bootstrapping? $50K MRR, profitable, 2 co-founders",
        "author": "bootstrap_or_raise",
        "score": 456,
        "num_comments": 178,
        "upvote_ratio": 0.87,
        "url": "",
        "selftext": "We're at $50K MRR, profitable, 2 co-founders. Both technical. 6-person team. Product: AI sales assistant for B2B. No debt, no funding. We have 2 offers: 1) Seed round: $1M at $8M valuation. 2) Keep bootstrapping. We're torn. Pros of raising: accelerate hiring, expand to enterprise, build brand. Pros of bootstrapping: keep equity, keep control, no board meetings, no pressure to grow fast. We're making $300K/year each in profit. Lifestyle is good. But we feel like we're missing the big opportunity. What would you do? Context: both founders are 30, no kids, no mortgage. We could take risks. But we also like sleeping well at night. Advice from founders who've been here?",
        "created_utc": 1746100000,
        "permalink": "https://www.reddit.com/r/startups/comments/startup_005/",
        "extracted_summary": "Should I raise a seed round or keep bootstrapping? $50K MRR, profitable, 2 co-founders. We're at $50K MRR, profitable, 2 co-founders...",
        "has_revenue_info": 1,
        "revenue_pattern": "$50K MRR, $1M, $8M valuation, $300K/year, $50K MRR",
        "tech_stack": "",
        "target_audience": "b2b, founder",
        "pain_point": "bootstrap or raise",
        "sentiment": "neutral",
        "category": "hiring_team",
        "fetched_at": "2025-06-17T02:00:00+00:00",
        "extracted_at": "2025-06-17T02:00:00+00:00",
        "created_date": "2025-05-02"
    },
    {
        "id": "entrepreneur_005",
        "subreddit": "Entrepreneur",
        "title": "I went from $0 to $250K in 1 year as a solo founder — the honest playbook (no fluff)",
        "author": "honest_playbook_guy",
        "score": 1567,
        "num_comments": 298,
        "upvote_ratio": 0.97,
        "url": "",
        "selftext": "I made $250K in my first year as a solo founder. No fluff, no inspirational quotes. Just what I actually did. Month 1-2: Built a SaaS for dentists (appointment reminders). Cold emailed 200 dental offices. 5 replied. 3 signed up. $49/mo. Month 3-6: Added SMS, reviews, payments. Raised price to $200/mo. 20 customers. Month 7-9: Added AI chatbot. $500/mo tier. 35 customers. Month 10-12: White-label option. $1,000/mo. 50 customers. $250K revenue. Tech: Next.js, Supabase, Twilio, Stripe, OpenAI. Cold email strategy: 200 emails, 50 replies, 25 demos, 15 conversions. Then referrals. Now at 80 customers, $350K projected. Solo. 40 hours/week. 70% margin. The boring truth: it's not about the idea. It's about doing the boring work every day for a year.",
        "created_utc": 1746000000,
        "permalink": "https://www.reddit.com/r/Entrepreneur/comments/entrepreneur_005/",
        "extracted_summary": "I went from $0 to $250K in 1 year as a solo founder — the honest playbook (no fluff). I made $250K in my first year as a solo founder...",
        "has_revenue_info": 1,
        "revenue_pattern": "$250K, $49/mo, $200/mo, $500/mo, $1,000/mo, $250K revenue, $350K, $250K",
        "tech_stack": "next.js, supabase, twilio, stripe, openai",
        "target_audience": "dentist, small business",
        "pain_point": "appointment reminders",
        "sentiment": "positive",
        "category": "revenue_share",
        "fetched_at": "2025-06-17T02:00:00+00:00",
        "extracted_at": "2025-06-17T02:00:00+00:00",
        "created_date": "2025-05-01"
    },
    {
        "id": "bootstrapped_005",
        "subreddit": "bootstrapped",
        "title": "How HoneyBook's $140M ARR validated the freelancer CRM market — and how indie hackers are winning it",
        "author": "market_validator",
        "score": 345,
        "num_comments": 67,
        "upvote_ratio": 0.86,
        "url": "",
        "selftext": "HoneyBook: $140M ARR, $498M raised, $2.4B valuation. This proves freelancers pay for client management. But here's the indie hacker angle: Dubsado: profitable, 15K+ customers. Bonsai: $9.4M raised, 100+ countries. Plutio: organic growth, $49/mo Pro tier. Bloom.io: gained traction after HoneyBook price hike. Indie hackers are proving the micro-SaaS model: solo founder, $5K-$20K MRR in first year. The playbook: 1) Pick a vertical (photographers, designers, consultants). 2) Build a simple tool. 3) Charge $15-$50/mo. 4) Market on Reddit and Twitter. No VC needed. The switching behavior is real. When HoneyBook raised prices, competitors captured 20%+ of the churn. Freelancers have low lock-in. They'll switch for better value.",
        "created_utc": 1745900000,
        "permalink": "https://www.reddit.com/r/bootstrapped/comments/bootstrapped_005/",
        "extracted_summary": "How HoneyBook's $140M ARR validated the freelancer CRM market — and how indie hackers are winning it. HoneyBook: $140M ARR...",
        "has_revenue_info": 1,
        "revenue_pattern": "$140M ARR, $498M, $2.4B valuation, $9.4M, $49/mo, $5K-$20K MRR, $15-$50/mo",
        "tech_stack": "",
        "target_audience": "freelancer, photographer, designer, consultant",
        "pain_point": "client management",
        "sentiment": "positive",
        "category": "idea_validation",
        "fetched_at": "2025-06-17T02:00:00+00:00",
        "extracted_at": "2025-06-17T02:00:00+00:00",
        "created_date": "2025-04-30"
    },
    {
        "id": "sideproject_005",
        "subreddit": "SideProject",
        "title": "My first 8 months as a solo founder — from idea to $2K MRR",
        "author": "8_month_journey",
        "score": 445,
        "num_comments": 89,
        "upvote_ratio": 0.90,
        "url": "",
        "selftext": "Month 1: Had an idea. Month 2: Built MVP. Month 3: Launched on Product Hunt. 50 signups. Month 4: $0 MRR. Realized no one wanted it. Month 5: Pivoted to a different feature. 5 paying customers. Month 6: $500 MRR. Added a second pricing tier. Month 7: $1,200 MRR. Started content marketing. Month 8: $2,000 MRR. 40 customers. Product: a tool that helps small businesses manage their Google reviews. Tech: React, Node.js, MongoDB, Vercel. Marketing: Product Hunt, Reddit, SEO blog posts. I work 25 hours/week on this, 15 hours on consulting. Goal: $5K MRR by month 12, then go full-time. The first 4 months were brutal. The last 4 months were exciting. Rollercoaster. Wouldn't trade it.",
        "created_utc": 1745800000,
        "permalink": "https://www.reddit.com/r/SideProject/comments/sideproject_005/",
        "extracted_summary": "My first 8 months as a solo founder — from idea to $2K MRR. Month 1: Had an idea. Month 2: Built MVP. Month 3: Launched on Product Hunt...",
        "has_revenue_info": 1,
        "revenue_pattern": "$2K MRR, $500 MRR, $1,200 MRR, $2,000 MRR, $5K MRR, $0 MRR",
        "tech_stack": "react, node.js, mongodb, vercel",
        "target_audience": "small business",
        "pain_point": "manage their Google reviews",
        "sentiment": "positive",
        "category": "revenue_share",
        "fetched_at": "2025-06-17T02:00:00+00:00",
        "extracted_at": "2025-06-17T02:00:00+00:00",
        "created_date": "2025-04-29"
    },
    {
        "id": "experienceddevs_006",
        "subreddit": "ExperiencedDevs",
        "title": "We replaced 50 microservices with a monolith and saved $15K/month",
        "author": "monolith_advocate",
        "score": 823,
        "num_comments": 201,
        "upvote_ratio": 0.94,
        "url": "",
        "selftext": "We had 50 microservices on Kubernetes. 12 engineers. $18K/month infrastructure. Debugging was a nightmare. We consolidated to a monolith. 4 engineers. $3K/month. Same traffic. Better performance. Here's what we did: 1) Identified 3 core domains. 2) Merged all services into 3 monolithic apps. 3) Simplified deployment to one command. 4) Reduced DB connections from 500 to 30. 5) Eliminated 15 internal APIs. 6) Cut CI/CD time from 45 min to 8 min. Result: engineers are happier, bugs are easier to find, new features ship faster. The monolith is a Django app + React frontend + PostgreSQL + Redis. Deployed on Railway. $3K/month. We were over-engineered. Most startups are. The lesson: start simple. Add complexity only when you have to. Not before. We're at $2M ARR. This simplified stack will scale to $10M easily.",
        "created_utc": 1745700000,
        "permalink": "https://www.reddit.com/r/ExperiencedDevs/comments/experienceddevs_006/",
        "extracted_summary": "We replaced 50 microservices with a monolith and saved $15K/month. We had 50 microservices on Kubernetes. 12 engineers...",
        "has_revenue_info": 1,
        "revenue_pattern": "$18K/month, $3K/month, $15K/month, $2M ARR, $10M",
        "tech_stack": "django, react, postgres, redis, kubernetes, railway",
        "target_audience": "developer, team",
        "pain_point": "over-engineered, debugging nightmare",
        "sentiment": "positive",
        "category": "tech_stack",
        "fetched_at": "2025-06-17T02:00:00+00:00",
        "extracted_at": "2025-06-17T02:00:00+00:00",
        "created_date": "2025-04-28"
    },
    {
        "id": "startup_ideas_005",
        "subreddit": "Startup_Ideas",
        "title": "Looking for feedback: AI tool that generates investor update emails from your metrics",
        "author": "investor_update_ai",
        "score": 178,
        "num_comments": 56,
        "upvote_ratio": 0.81,
        "url": "",
        "selftext": "I hate writing investor update emails. Every month, same format. I built an AI tool that connects to Stripe, Google Analytics, and your project management tool, then generates a professional investor update email. Includes: MRR growth, churn, new customers, milestones, upcoming goals. Currently in beta with 3 founders. All love it. Pricing: free for 1 update/mo, $29/mo for unlimited. Questions: 1) Is this a real pain? 2) Would you pay $29/mo? 3) What integrations should I add? Tech: Next.js, OpenAI API, Stripe API, GA API. Built in 1 week. No customers yet. Just looking for honest feedback. Thanks!",
        "created_utc": 1745600000,
        "permalink": "https://www.reddit.com/r/Startup_Ideas/comments/startup_ideas_005/",
        "extracted_summary": "Looking for feedback: AI tool that generates investor update emails from your metrics. I hate writing investor update emails...",
        "has_revenue_info": 0,
        "revenue_pattern": "$29/mo",
        "tech_stack": "next.js, openai, stripe api",
        "target_audience": "founder, investor",
        "pain_point": "hate writing investor update emails",
        "sentiment": "neutral",
        "category": "idea_validation",
        "fetched_at": "2025-06-17T02:00:00+00:00",
        "extracted_at": "2025-06-17T02:00:00+00:00",
        "created_date": "2025-04-27"
    },
    {
        "id": "saas_008",
        "subreddit": "SaaS",
        "title": "The psychology of SaaS pricing: why $99/mo converts better than $79/mo (with data)",
        "author": "pricing_psychologist_v2",
        "score": 678,
        "num_comments": 145,
        "upvote_ratio": 0.91,
        "url": "",
        "selftext": "We tested $79 vs $99/mo for our B2B SaaS. $99 converted 12% better. Here's why: 1) Price anchoring. We showed $199/mo as the 'enterprise' plan first. $99 felt like a deal. 2) Value perception. At $99, customers expect more features. We delivered. At $79, they expected less. 3) Churn paradox. Higher price = higher perceived value = lower churn. Our $99 customers had 2.1% churn vs 3.8% for $79. 4) Annual discount effect. At $99, our annual plan ($990/year) felt like a real deal. 45% chose annual. At $79, only 30% chose annual. Net result: $99 plan generated 34% more revenue per customer. The lesson: test higher prices. The market often rewards it. We were scared to charge $99. We shouldn't have been. MRR: $85K. ARR: $1.02M. 1,000 customers.",
        "created_utc": 1745500000,
        "permalink": "https://www.reddit.com/r/SaaS/comments/saas_008/",
        "extracted_summary": "The psychology of SaaS pricing: why $99/mo converts better than $79/mo (with data). We tested $79 vs $99/mo for our B2B SaaS...",
        "has_revenue_info": 1,
        "revenue_pattern": "$79, $99/mo, $199/mo, $990/year, $85K MRR, $1.02M ARR, $99",
        "tech_stack": "",
        "target_audience": "b2b, saas",
        "pain_point": "scared to charge",
        "sentiment": "positive",
        "category": "revenue_share",
        "fetched_at": "2025-06-17T02:00:00+00:00",
        "extracted_at": "2025-06-17T02:00:00+00:00",
        "created_date": "2025-04-26"
    },
    {
        "id": "indiehackers_007",
        "subreddit": "indiehackers",
        "title": "I built an AI wrapper that makes $40K MRR — here's the honest truth about 'no moat' businesses",
        "author": "ai_wrapper_honest",
        "score": 1234,
        "num_comments": 456,
        "upvote_ratio": 0.88,
        "url": "",
        "selftext": "I built an AI wrapper. $40K MRR. 2,800 customers. No moat. Anyone can copy it. Here's why it still works: 1) First-mover advantage. I launched 18 months ago. The market knows me. 2) SEO. I rank #1 for 15 keywords. Copycats start from 0. 3) Brand. Customers trust me. Copycats don't have that. 4) Iteration speed. I ship weekly. Copycats ship monthly. 5) Customer support. I answer every email in 2 hours. Copycats can't afford that. 6) Pricing. I'm cheaper than building it yourself. The 'no moat' argument is lazy. Every business has moats if you build them. They just look different for AI wrappers. The moat is speed, brand, and customer love. Not technology. Tech: React, Node.js, OpenAI API, Stripe. Hosted on Vercel. Solo founder. $40K MRR. 87% margin. No team. No office. Just me and a laptop. 3 hours of support per day. 5 hours of coding. The rest is sleep.",
        "created_utc": 1745400000,
        "permalink": "https://www.reddit.com/r/indiehackers/comments/indiehackers_007/",
        "extracted_summary": "I built an AI wrapper that makes $40K MRR — here's the honest truth about 'no moat' businesses. I built an AI wrapper. $40K MRR...",
        "has_revenue_info": 1,
        "revenue_pattern": "$40K MRR, $40K MRR, 87%",
        "tech_stack": "react, node.js, openai, stripe, vercel",
        "target_audience": "developer, indie hacker",
        "pain_point": "no moat",
        "sentiment": "positive",
        "category": "revenue_share",
        "fetched_at": "2025-06-17T02:00:00+00:00",
        "extracted_at": "2025-06-17T02:00:00+00:00",
        "created_date": "2025-04-25"
    },
    {
        "id": "entrepreneur_006",
        "subreddit": "Entrepreneur",
        "title": "My first year of entrepreneurship: $0 to $65K/month as a content agency for SaaS",
        "author": "content_agency_founder",
        "score": 890,
        "num_comments": 167,
        "upvote_ratio": 0.93,
        "url": "",
        "selftext": "Year 1: $0. Quit my job as a marketing manager. Started a content agency. Fired my first client (toxic). Lost $15K on a failed e-commerce experiment. Year 2: $15K/mo. Narrowed to SEO + content for SaaS. Hired 2 contractors. $35K/mo. Added link building. $65K/mo. Now at $65K/mo with 8 team members (all contractors). Profit margin: 45%. I work 35 hours/week. Key insight: niche down early. I was a generalist for 8 months and made nothing. The moment I said 'I only do SEO for SaaS' everything changed. No office. No VC. No debt. Just a laptop, a team of contractors, and a narrow niche. The $65K/mo is 45% profit. $350K/year take-home. Better than my $120K marketing manager salary. And I set my own hours.",
        "created_utc": 1745300000,
        "permalink": "https://www.reddit.com/r/Entrepreneur/comments/entrepreneur_006/",
        "extracted_summary": "My first year of entrepreneurship: $0 to $65K/month as a content agency for SaaS. Year 1: $0. Quit my job as a marketing manager...",
        "has_revenue_info": 1,
        "revenue_pattern": "$65K/month, $15K/mo, $35K/mo, $65K/mo, $350K/year, $120K, $65K/month",
        "tech_stack": "",
        "target_audience": "saas, marketing manager",
        "pain_point": "generalist",
        "sentiment": "positive",
        "category": "lessons_learned",
        "fetched_at": "2025-06-17T02:00:00+00:00",
        "extracted_at": "2025-06-17T02:00:00+00:00",
        "created_date": "2025-04-24"
    }
]


def seed_mock_data():
    """将模拟数据写入数据库和 JSON 文件"""
    # 1. 写入 SQLite
    conn = sqlite3.connect(os.path.join(DATA_DIR, "posts.db"))
    c = conn.cursor()
    c.execute('''
        CREATE TABLE IF NOT EXISTS posts (
            id TEXT PRIMARY KEY, subreddit TEXT, title TEXT, author TEXT,
            score INTEGER, num_comments INTEGER, upvote_ratio REAL, url TEXT,
            selftext TEXT, created_utc REAL, permalink TEXT, extracted_summary TEXT,
            has_revenue_info INTEGER, revenue_pattern TEXT, tech_stack TEXT,
            target_audience TEXT, pain_point TEXT, sentiment TEXT, category TEXT,
            fetched_at TEXT, extracted_at TEXT
        )
    ''')
    for post in MOCK_POSTS:
        c.execute('''
            INSERT OR REPLACE INTO posts VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
        ''', (
            post["id"], post["subreddit"], post["title"], post["author"],
            post["score"], post["num_comments"], post["upvote_ratio"], post["url"],
            post["selftext"], post["created_utc"], post["permalink"], post["extracted_summary"],
            post["has_revenue_info"], post["revenue_pattern"], post["tech_stack"],
            post["target_audience"], post["pain_point"], post["sentiment"], post["category"],
            post["fetched_at"], post["extracted_at"]
        ))
    conn.commit()
    conn.close()
    print(f"[SEED] {len(MOCK_POSTS)} posts inserted into DB")

    # 2. 写入 JSON
    json_path = os.path.join(DATA_DIR, "posts.json")
    with open(json_path, "w", encoding="utf-8") as f:
        json.dump(MOCK_POSTS, f, ensure_ascii=False, indent=2)
    print(f"[SEED] {len(MOCK_POSTS)} posts written to {json_path}")


if __name__ == "__main__":
    seed_mock_data()
